ignored:
  # ignore apt version pinning
  - DL3008
  # ignore pip version pinning
  - DL3013
  # ignore npm version pinning
  - DL3016
  # ignore apk version pinning
  - DL3018
  # ignore RUN consider consolidation
  - DL3059
